/*
 * GPIO_CFH.h
 *
 *  Created on: Oct 11, 2019
 *      Author: Dyaa Elshater
 */

#ifndef GPIO_CFG_H_
#define GPIO_CFG_H_

/********************************************************/
/** Descrption	:	Configure the Pins Mode 			*/
/*														*/
/*						  -GPIO_INPUT_ANALOG			*/
/*                        -GPIO_INPUT_FLOATING			*/
/*                        -GPIO_INPUT_PULL_UP_DOWN		*/
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_10MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_10MHZ */
/*                        -GPIO_AF_PUSH_PULL_10MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_10MHZ	    */
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_2MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_2MHZ	*/
/*                        -GPIO_AF_PUSH_PULL_2MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_2MHZ		*/
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_50MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_50MHZ */
/*                        -GPIO_AF_PUSH_PULL_50MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_50MHZ		*/
/****************************************************/
		/*Port A*/
#define GPIO_MODE_u8RA_0		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RA_15		GPIO_INPUT_FLOATING
		/*Port B*/
#define GPIO_MODE_u8RB_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RB_15		GPIO_INPUT_FLOATING
		/*Port C*/
#define GPIO_MODE_u8RC_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RC_15		GPIO_INPUT_FLOATING
		/*Port D*/
#define GPIO_MODE_u8RD_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_15		GPIO_INPUT_FLOATING
		/*Port E*/
#define GPIO_MODE_u8RE_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_15		GPIO_INPUT_FLOATING
		/*Port F*/
#define GPIO_MODE_u8RF_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_15		GPIO_INPUT_FLOATING
		/*Port G*/
#define GPIO_MODE_u8RG_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_15		GPIO_INPUT_FLOATING


/** Descrption	:	In INPUT PULL UP/DOWN Determine the Pull MODE			*/
/*							- GPIO_PULL_UP									*/
/*							- GPIO_PULL_DOWN								*/
/*																			*/
		/*Port A*/
#define GPIO_PUPD_u8RA_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_15		GPIO_PULL_DOWN
		/*Port B*/
#define GPIO_PUPD_u8RB_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_15		GPIO_PULL_DOWN
		/*Port C*/
#define GPIO_PUPD_u8RC_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_15		GPIO_PULL_DOWN
		/*Port D*/
#define GPIO_PUPD_u8RD_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_15		GPIO_PULL_DOWN
		/*Port E*/
#define GPIO_PUPD_u8RE_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_15		GPIO_PULL_DOWN
		/*Port F*/
#define GPIO_PUPD_u8RF_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_15		GPIO_PULL_DOWN
		/*Port G*/
#define GPIO_PUPD_u8RG_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_15		GPIO_PULL_DOWN








#endif /* GPIO_CFG_H_ */
