/****************************************************************/
/**	Name		:	Dyaa Elshater								*/
/**	Date		:	8/8/2020									*/
/**	Description	:	External Interrupt Configuration file		*/
/** MCU			:	STM32F103C8									*/
/**	Version		:	2.0 V									`	*/
/****************************************************************/

#ifndef EXTI_CFG_H_
#define EXTI_CFG_H_

/** Configure the Interrupt mask enable for EXTI					*/
/*			EXTIx_IMR_EN	:										*/
/*							-	EXTI_DISABLE						*/
/*							-	EXTI_ENABLE						*/
#define EXTI0_IMR_EN		EXTI_DISABLE
#define EXTI1_IMR_EN		EXTI_DISABLE
#define EXTI2_IMR_EN		EXTI_DISABLE
#define EXTI3_IMR_EN		EXTI_DISABLE
#define EXTI4_IMR_EN		EXTI_DISABLE
#define EXTI5_IMR_EN		EXTI_DISABLE
#define EXTI6_IMR_EN		EXTI_DISABLE
#define EXTI7_IMR_EN		EXTI_DISABLE
#define EXTI8_IMR_EN		EXTI_DISABLE
#define EXTI9_IMR_EN		EXTI_DISABLE
#define EXTI10_IMR_EN		EXTI_DISABLE
#define EXTI11_IMR_EN		EXTI_DISABLE
#define EXTI12_IMR_EN		EXTI_DISABLE
#define EXTI13_IMR_EN		EXTI_DISABLE
#define EXTI14_IMR_EN		EXTI_DISABLE
#define EXTI15_IMR_EN		EXTI_DISABLE
#define EXTI16_IMR_EN		EXTI_DISABLE
#define EXTI17_IMR_EN		EXTI_DISABLE
#define EXTI18_IMR_EN		EXTI_DISABLE
#define EXTI19_IMR_EN		EXTI_DISABLE

/** Configure the Evet mask enable for EXTI						*/
/*			EXTIx_EMR_EN	:										*/
/*							-	EXTI_DISABLE						*/
/*							-	EXTI_ENABLE						*/
#define EXTI0_EMR_EN		EXTI_DISABLE
#define EXTI1_EMR_EN		EXTI_DISABLE
#define EXTI2_EMR_EN		EXTI_DISABLE
#define EXTI3_EMR_EN		EXTI_DISABLE
#define EXTI4_EMR_EN		EXTI_DISABLE
#define EXTI5_EMR_EN		EXTI_DISABLE
#define EXTI6_EMR_EN		EXTI_DISABLE
#define EXTI7_EMR_EN		EXTI_DISABLE
#define EXTI8_EMR_EN		EXTI_DISABLE
#define EXTI9_EMR_EN		EXTI_DISABLE
#define EXTI10_EMR_EN		EXTI_DISABLE
#define EXTI11_EMR_EN		EXTI_DISABLE
#define EXTI12_EMR_EN		EXTI_DISABLE
#define EXTI13_EMR_EN		EXTI_DISABLE
#define EXTI14_EMR_EN		EXTI_DISABLE
#define EXTI15_EMR_EN		EXTI_DISABLE
#define EXTI16_EMR_EN		EXTI_DISABLE
#define EXTI17_EMR_EN		EXTI_DISABLE
#define EXTI18_EMR_EN		EXTI_DISABLE
#define EXTI19_EMR_EN		EXTI_DISABLE

/** Configure the Rising trigger for EXTI						*/
/*	EXTIx_RISING_DETECTION_EN	:								*/
/*							-	EXTI_DISABLE						*/
/*							-	EXTI_ENABLE						*/
#define EXTI0_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI1_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI2_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI3_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI4_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI5_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI6_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI7_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI8_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI9_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI10_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI11_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI12_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI13_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI14_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI15_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI16_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI17_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI18_RISING_DETECTION_EN		EXTI_DISABLE
#define EXTI19_RISING_DETECTION_EN		EXTI_DISABLE

/** Configure the Falling trigger for EXTI						*/
/*	EXTIx_FALLING_DETECTION_EN	:								*/
/*							-	EXTI_DISABLE						*/
/*							-	EXTI_ENABLE						*/
#define EXTI0_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI1_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI2_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI3_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI4_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI5_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI6_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI7_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI8_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI9_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI10_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI11_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI12_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI13_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI14_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI15_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI16_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI17_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI18_FALLING_DETECTION_EN		EXTI_DISABLE
#define EXTI19_FALLING_DETECTION_EN		EXTI_DISABLE

#endif /* EXTI_CFG_H_ */
