/*
 * GPIO_CFH.h
 *
 *  Created on: Oct 11, 2019
 *      Author: Dyaa Elshater
 */

#ifndef GPIO_CFG_H_
#define GPIO_CFG_H_

/********************************************************/
/** Descrption	:	Configure the Pins Mode 			*/
/*														*/
/*						  -GPIO_INPUT_ANALOG			*/
/*                        -GPIO_INPUT_FLOATING			*/
/*                        -GPIO_INPUT_PULL_UP_DOWN		*/
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_10MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_10MHZ */
/*                        -GPIO_AF_PUSH_PULL_10MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_10MHZ	    */
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_2MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_2MHZ	*/
/*                        -GPIO_AF_PUSH_PULL_2MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_2MHZ		*/
/*                                                      */
/*                        -GPIO_OUTPUT_PUSH_PULL_50MHZ	*/
/*                        -GPIO_OUTPUT_OPEN_DRAIN_50MHZ */
/*                        -GPIO_AF_PUSH_PULL_50MHZ		*/
/*                        -GPIO_AF_OPEN_DRAIN_50MHZ		*/
/****************************************************/
		/*Port A*/
#define GPIO_MODE_u8RA_0		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_1		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_2		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_3		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_4		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_5		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_6		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_7		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_8		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_9		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_10		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_11		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_12		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_13		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_14		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RA_15		GPIO_OUTPUT_PUSH_PULL_50MHZ
		/*Port B*/
#define GPIO_MODE_u8RB_0		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_1		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_2		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_3		GPIO_OUTPUT_PUSH_PULL_50MHZ
#define GPIO_MODE_u8RB_4		GPIO_OUTPUT_PUSH_PULL_50MHZ
#define GPIO_MODE_u8RB_5		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_6		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_7		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_8		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_9		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_10		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_11		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_12		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_13		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_14		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RB_15		GPIO_OUTPUT_PUSH_PULL_10MHZ
		/*Port C*/
#define GPIO_MODE_u8RC_0		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_1		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_2		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_3		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_4		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_5		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_6		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_7		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_8		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_9		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_10		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_11		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_12		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_13		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_14		GPIO_OUTPUT_PUSH_PULL_10MHZ
#define GPIO_MODE_u8RC_15		GPIO_OUTPUT_PUSH_PULL_10MHZ
		/*Port D*/
#define GPIO_MODE_u8RD_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RD_15		GPIO_INPUT_FLOATING
		/*Port E*/
#define GPIO_MODE_u8RE_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RE_15		GPIO_INPUT_FLOATING
		/*Port F*/
#define GPIO_MODE_u8RF_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RF_15		GPIO_INPUT_FLOATING
		/*Port G*/
#define GPIO_MODE_u8RG_0		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_1		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_2		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_3		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_4		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_5		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_6		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_7		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_8		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_9		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_10		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_11		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_12		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_13		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_14		GPIO_INPUT_FLOATING
#define GPIO_MODE_u8RG_15		GPIO_INPUT_FLOATING


/** Descrption	:	In INPUT PULL UP/DOWN Determine the Pull MODE			*/
/*							- GPIO_PULL_UP									*/
/*							- GPIO_PULL_DOWN								*/
/*																			*/
		/*Port A*/
#define GPIO_PUPD_u8RA_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RA_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RA_15		GPIO_PULL_DOWN
		/*Port B*/
#define GPIO_PUPD_u8RB_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RB_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RB_15		GPIO_PULL_DOWN
		/*Port C*/
#define GPIO_PUPD_u8RC_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RC_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RC_15		GPIO_PULL_DOWN
		/*Port D*/
#define GPIO_PUPD_u8RD_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RD_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RD_15		GPIO_PULL_DOWN
		/*Port E*/
#define GPIO_PUPD_u8RE_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RE_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RE_15		GPIO_PULL_DOWN
		/*Port F*/
#define GPIO_PUPD_u8RF_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RF_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RF_15		GPIO_PULL_DOWN
		/*Port G*/
#define GPIO_PUPD_u8RG_0		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_1		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_2		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_3		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_4		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_5		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_6		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_7		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_8		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_9		GPIO_PULL_DOWN	
#define GPIO_PUPD_u8RG_10		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_11		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_12		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_13		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_14		GPIO_PULL_DOWN
#define GPIO_PUPD_u8RG_15		GPIO_PULL_DOWN




/******//****************************************************/
		/** 	Alternate Function Configuration			*/
/*SW and JTAG Configuration									*/
/* 	JTAG_SW_CFG 	:										*/
/*					-JTAG_ENABLE_SW_ENABLE_RESET_STATE		*/
/*			 		-JTAG_ENABLE_SW_ENABLE_WITHOUT_RESET	*/
/* 					-JTAG_DISABLE_SW_ENABEL					*/
/*					-JTAG_DISABLE_SW_DISABLE				*/
#define JTAG_SW_CFG		JTAG_DISABLE_SW_ENABEL

/*	ADC Configuration										*/
/*		ADCx_REGULAR_CGF	:								*/
/*					-ADCx_REGULAR_CONNECTED_TO_EXTI11		*/
/*		 			-ADCx_REGULAR_CONNECTED_TO_TIM8_TRIGo 	*/
/*		ADCx_INJECTED_CFD	:								*/
/*					-ADCx_INJECTED_CONNECTED_TO_EXTI15		*/
/*					-ADCx_INJECTED_CONNECTED_TO_TIM8_TRICH4	*/
#define	ADC1_REGULAR_CFG	ADC1_REGULAR_CONNECTED_TO_EXTI11
#define ADC1_INJECTED_CFG	ADC1_INJECTED_CONNECTED_TO_EXTI15
#define	ADC2_REGULAR_CFG	ADC2_REGULAR_CONNECTED_TO_EXTI11
#define ADC2_INJECTED_CFG	ADC2_INJECTED_CONNECTED_TO_EXTI15

/*	Oscillator Configuration	to PD0 and PD1				*/
/*					OSC_CFG		:							*/
/*								-AFIO_ENABLE				*/
/*								-AFIO_DISABLE				*/
#define OSC_CFG		AFIO_ENABLE

/*	CAN Configuration										*/
/*			CAN_CFG		:									*/
/*						-CAN_MAPPED_TO_PA11_PA12			*/
/*						-CAN_MAPPED_TO_PB8_PB9				*/
/*						-CAN_MAPPED_TO_PD0_PD1				*/
#define CAN_CFG			CAN_MAPPED_TO_PA11_PA12

	/************************ Timers **************************/
/*	Timer 1 Remapping										*/
/*		TIM1_Remap_CFG	:									*/
/*	-TIMER1_ETR_PA12_CH1_PA8_CH2_PA9_CH3_PA10_CH4_PA11_BKIN_PB12_CH1N_PB13_CH2N_PB14_CH3N_PB15		*/
/*	-TIMER1_ETR_PA12_CH1_PA8_CH2_PA9_CH3_PA10_CH4_PA11_BKIN_PA6_CH1N_PA7_CH2N_PB0_CH3N_PB1			*/
/*	-TIMER1_ETR_PE7_CH1_PE9_CH2_PE11_CH3_PE13_CH4_PE14_BKIN_PE15_CH1N_PE8_CH2N_PE10_CH3N_PE12		*/
#define TIM1_Remap_CFG	TIMER1_ETR_PA12_CH1_PA8_CH2_PA9_CH3_PA10_CH4_PA11_BKIN_PB12_CH1N_PB13_CH2N_PB14_CH3N_PB15

/*	Timer 2 Remapping										*/
/*		TIM2_Remap_CFG	:									*/
/*			-TIMER2_CH1_ETR_PA0_CH2_PA1_CH3_PA2_CH4_PA3		*/
/*			-TIMER2_CH1_ETR_PA15_CH2_PB3_CH3_PA2_CH4_PA3	*/
/*			-TIMER2_CH1_ETR_PA0_CH2_PA1_CH3_PB10_CH4_PB11	*/
/*			-TIMER2_CH1_ETR_PA15_CH2_PB3_CH3_PB10_CH4_PB11	*/
#define TIM2_Remap_CFG	TIMER2_CH1_ETR_PA0_CH2_PA1_CH3_PA2_CH4_PA3

/*	Timer 3	Remapping										*/
/*		TIM3_Remap_CFG	:									*/
/*				-TIMER3_CH1_PA6_CH2_PA7_CH3_PB0_CH4_PB1		*/
/*				-TIMER3_CH1_PB4_CH2_PB5_CH3_PB0_CH4_PB1		*/
/*				-TIMER3_CH1_PC6_CH2_PC7_CH3_PC8_CH4_PC9		*/
#define TIM3_Remap_CFG	TIMER3_CH1_PA6_CH2_PA7_CH3_PB0_CH4_PB1

/*	Timer 4 Remapping										*/
/*		TIM4_Remap_CFG	:									*/
/*				-TIMER4_CH1_PB6_CH2_PB7_CH3_PB8_CH4_PB9		*/
/*				-TIMER4_CH1_PD12_CH2_PD13_CH3_PD14_CH4_PD15	*/
#define TIM4_Remap_CFG	TIMER4_CH1_PB6_CH2_PB7_CH3_PB8_CH4_PB9


/*	Timer5 Channel 4										*/
/*			TIM5_CH4_CGF	:								*/
/*					-TIM5_CH4_TO_PA3						*/
/*					-TIM5_CH4_TO_LSI						*/
#define TIM5_CH4_CGF	TIM5_CH4_TO_PA3

/*	Timer 9 Configuration									*/
/*			TIM9_CFG	:									*/
/*						-	TIMER9_CH1_PA2_CH2_PA9			*/
/*						-	TIMER9_CH1_PE5_CH2_PE6			*/
#define TIM9_CFG	TIMER9_CH1_PA2_CH2_PA9

/*	Timer 10 Configuration									*/
/*			TIM10_CFG	:									*/
/*						-	TIMER10_CH1_to_PB8				*/
/*						-	TIMER10_CH1_to_PF6				*/
#define TIM10_CFG	TIMER10_CH1_to_PB8

/*	Timer 11 Configuration									*/
/*			TIM11_CFG	:									*/
/*						-	TIMER11_CH1_to_PB9				*/
/*						-	TIMER11_CH1_to_PF7				*/
#define TIM11_CFG	TIMER11_CH1_to_PB9

/*	Timer 13 Configuration									*/
/*			TIM13_CFG	:									*/
/*						-	TIMER13_CH1_to_PA6				*/
/*						-	TIMER13_CH1_to_PF8				*/
#define TIM13_CFG	TIMER13_CH1_to_PA6

/*	Timer 14 Configuration									*/
/*			TIM14_CFG	:									*/
/*						-	TIMER14_CH1_to_PA7				*/
/*						-	TIMER14_CH1_to_PF9				*/
#define TIM14_CFG	TIMER14_CH1_to_PA7


	/********************* Communication protocols ****************/

/*	USART 1 Remapping										*/
/*		USART2_Remap_CFG :									*/
/*		-USART1_TX_PA9_RX_PA10								*/
/*		-USART1_TX_PB6_RX_PB7								*/
#define USART1_Remap_CFG	USART2_CTS_PA0_RTS_PA1_TX_PA2_RX_PA3_CK_PA4

/*	USART 2 Remapping										*/
/*		USART2_Remap_CFG :									*/
/*		-USART2_CTS_PA0_RTS_PA1_TX_PA2_RX_PA3_CK_PA4		*/
/*		-USART2_CTS_PD3_RTS_PD4_TX_PD5_RX_PD6_CK_PD7		*/
#define USART2_Remap_CFG	USART2_CTS_PA0_RTS_PA1_TX_PA2_RX_PA3_CK_PA4

/*	USART 3 Remapping										*/
/*		USART3_Remap_CFG :									*/
/*		-USART3_TX_PB10_RX_PB11_CK_PB12_CTS_PB13_RTS_PB14	*/
/*		-USART3_TX_PC10_RX_PC11_CK_PC12_CTS_PB13_RTS_PB14	*/
/*		-USART3_TX_PD8_RX_PD9_CK_PD10_CTS_PD11_RTS_PD12		*/
#define USART3_Remap_CFG	USART3_TX_PB10_RX_PB11_CK_PB12_CTS_PB13_RTS_PB14

/*	I2C 1 Remapping											*/
/*		I2C1_Remap_CFG :									*/
/*		-I2C1_SCL_PB6_SDA_PB7								*/
/*		-I2C1_SCL__B8_SDA_PB9								*/
#define I2C1_Remap_CFG	I2C1_SCL_PB6_SDA_PB7

/*	SPI 1 Remapping											*/
/*		SPI1_Remap_CFG :									*/
/*		-SPI1_NSS_PA4_SCK_PA5_MISO_PA6_MOSI_PA7				*/
/*		-SPI1_NSS_PA15_SCK_PB3_MISO_PB4_MOSI_PB5			*/
#define SPI1_Remap_CFG	SPI1_NSS_PA4_SCK_PA5_MISO_PA6_MOSI_PA7


/*	External Interrupt										*/
/*			EXTIn_CFG : 			n 0->15					*/
/*						-EXTI_PA							*/
/*						-EXTI_PB							*/
/*						-EXTI_PC							*/
/*						-EXTI_PD							*/
/*						-EXTI_PE							*/
/*						-EXTI_PF							*/
/*						-EXTI_PG							*/
#define EXTI0_CFG		EXTI_PA
#define EXTI1_CFG		EXTI_PA
#define EXTI2_CFG		EXTI_PA
#define EXTI3_CFG		EXTI_PA
#define EXTI4_CFG		EXTI_PA
#define EXTI5_CFG		EXTI_PA
#define EXTI6_CFG		EXTI_PA
#define EXTI7_CFG		EXTI_PA
#define EXTI8_CFG		EXTI_PA
#define EXTI9_CFG		EXTI_PA
#define EXTI10_CFG		EXTI_PA
#define EXTI11_CFG		EXTI_PA
#define EXTI12_CFG		EXTI_PA
#define EXTI13_CFG		EXTI_PA
#define EXTI14_CFG		EXTI_PA
#define EXTI15_CFG		EXTI_PA

/*	NAVD Connection											*/
/*	FSMC_NADV_CFG	:										*/
/*								-AFIO_ENABLE				*/
/*								-AFIO_DISABLE				*/
#define FSMC_NADV_CFG	AFIO_DISABLE



#endif /* GPIO_CFG_H_ */
